name: Deploy to GitHub Pages

on:
  push:
    branches: [ feat/hide-time ]
  workflow_dispatch: {}

# Garantir permissões necessárias para o GITHUB_TOKEN escrever na branch gh-pages
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site-example
          allow_empty_commit: true
